/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactComponent: typeof import('./src/components/ContactComponent.vue')['default']
    CreateProduct: typeof import('./src/components/CreateProduct.vue')['default']
    CreateProductModal: typeof import('./src/components/CreateProductModal.vue')['default']
    ExtData: typeof import('./src/components/ExtData.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InvoiceLineComponent: typeof import('./src/components/InvoiceLineComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    ProductComponent: typeof import('./src/components/ProductComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
